/**
 * Permalink for a precomputed demo trial: /dossier/TSLA etc.
 * Reads demos/<TICKER>.json generated by `npm run precompute` and prerenders
 * the full courtroom transcript at build time — instant, zero model calls.
 */
import { readdir, readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import type { TrialResult } from '../../../src/tribunal/run.js'
import { BillReceipt } from '../../components/court-bill'
import { Markdown } from '../../components/markdown'
import type { BillEntry } from '../../trial'
import { VerdictCard } from '../../verdict-card'

export const dynamicParams = false

type Demo = TrialResult & { generatedAt: string }

const demosDir = resolve(process.cwd(), 'demos')

export async function generateStaticParams() {
  const files = await readdir(demosDir).catch(() => [] as string[])
  return files.filter((f) => f.endsWith('.json')).map((f) => ({ ticker: f.replace(/\.json$/, '') }))
}

const loadDemo = async (ticker: string): Promise<Demo | null> => {
  if (!/^[A-Z0-9.-]{1,10}$/.test(ticker)) return null
  try {
    return JSON.parse(await readFile(resolve(demosDir, `${ticker}.json`), 'utf8')) as Demo
  } catch {
    return null
  }
}

export default async function DossierPage({ params }: { params: Promise<{ ticker: string }> }) {
  const { ticker } = await params
  const demo = await loadDemo(ticker.toUpperCase())
  if (!demo) notFound()

  const speeches = [
    { role: 'prosecutor', title: 'The Prosecution', text: demo.bearCase },
    { role: 'defense', title: 'The Defense', text: demo.defense },
    { role: 'prosecutor', title: 'The Prosecution — Rebuttal', text: demo.rebuttal },
  ]

  return (
    <main className="container">
      <header className="masthead">
        <div className="eyebrow">Precomputed Case File</div>
        <h1>SEC Tribunal</h1>
        <p>
          In re {demo.company.name} ({demo.company.ticker}) · CIK {demo.company.cik10} · tried {demo.generatedAt}
        </p>
      </header>

      <section className="speech">
        <div className="speech-head">
          <span className="speech-role clerk">Clerk of the Tribunal</span>
        </div>
        <div className="speech-body">
          Exhibit A: XBRL financial facts from SEC EDGAR 10-K/10-Q filings.
          {demo.peer ? ` Exhibit B: industry peer ${demo.peer.name} (${demo.peer.ticker}).` : ''}
        </div>
      </section>

      {speeches.map((s, i) => (
        <section key={i} className="speech">
          <div className="speech-head">
            <span className={`speech-role ${s.role}`}>{s.title}</span>
            <span className="speech-sub">In re {demo.company.name}</span>
          </div>
          <div className="speech-body">
            <Markdown text={s.text} />
          </div>
        </section>
      ))}

      <VerdictCard verdict={demo.verdict} />

      {demo.usage && (
        <BillReceipt
          entries={
            [
              { label: 'Prosecutor', usage: demo.usage.prosecutor },
              { label: 'Defense', usage: demo.usage.defense },
              { label: 'Prosecutor (rebuttal)', usage: demo.usage.rebuttal },
              { label: 'Judge', usage: demo.usage.judge },
            ] satisfies BillEntry[]
          }
        />
      )}

      <div className="actions">
        <Link className="link-button" href="/">
          Hold your own trial →
        </Link>
      </div>

      <footer className="footer">
        Precomputed demo · Data: SEC EDGAR XBRL companyfacts · Not investment advice.
      </footer>
    </main>
  )
}
