/**
 * Permalink for a precomputed demo trial: /dossier/TSLA etc.
 * Reads demos/<TICKER>.json generated by `npm run precompute` and prerenders
 * the full courtroom transcript at build time — instant, zero model calls.
 */
import { readdir, readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import type { TrialResult } from '../../../src/tribunal/run.js'
import { BillReceipt } from '../../components/court-bill'
import { DocketPanel } from '../../components/docket'
import { Markdown } from '../../components/markdown'
import type { BillEntry } from '../../trial'
import { VerdictCard } from '../../verdict-card'

export const dynamicParams = false

type Demo = TrialResult & { generatedAt: string }

const demosDir = resolve(process.cwd(), 'demos')

export async function generateStaticParams() {
  const files = await readdir(demosDir).catch(() => [] as string[])
  return files.filter((f) => f.endsWith('.json')).map((f) => ({ ticker: f.replace(/\.json$/, '') }))
}

const loadDemo = async (ticker: string): Promise<Demo | null> => {
  if (!/^[A-Z0-9.-]{1,10}$/.test(ticker)) return null
  try {
    return JSON.parse(await readFile(resolve(demosDir, `${ticker}.json`), 'utf8')) as Demo
  } catch {
    return null
  }
}

/** Plain-text preview for a collapsed speech's <summary> — strips markdown noise, keeps the first sentence. */
const firstSentence = (markdown: string): string => {
  const clean = markdown
    .split('\n')
    .filter((line) => !/^#{1,6}\s/.test(line.trim()) && line.trim() !== '---')
    .join(' ')
    .replace(/\*\*/g, '')
    .replace(/\*/g, '')
    .replace(/\s+/g, ' ')
    .trim()
  const match = clean.match(/^.*?[.!?](?=\s|$)/)
  return (match ? match[0] : clean.slice(0, 140)).trim()
}

export default async function DossierPage({ params }: { params: Promise<{ ticker: string }> }) {
  const { ticker } = await params
  const demo = await loadDemo(ticker.toUpperCase())
  if (!demo) notFound()

  const scribeIntro =
    'Exhibit A: XBRL financial facts from SEC EDGAR 10-K/10-Q filings.' +
    (demo.peer ? ` Exhibit B: industry peer ${demo.peer.name} (${demo.peer.ticker}).` : '')

  const speeches = [
    { role: 'prosecutor', title: 'The Skeptic — Prosecution', text: demo.bearCase },
    { role: 'defense', title: 'The Advocate — Defense', text: demo.defense },
    { role: 'prosecutor', title: 'The Skeptic — Rebuttal', text: demo.rebuttal },
  ]

  return (
    <main className="container">
      <header className="masthead">
        <div className="eyebrow">Precomputed Case File</div>
        <h1>SEC Tribunal</h1>
        <p className="case-register">
          Case No. {demo.company.cik10} · In re {demo.company.name} ({demo.company.ticker}) · tried{' '}
          {demo.generatedAt}
        </p>
      </header>

      <VerdictCard verdict={demo.verdict} />

      <details className="speech clerk">
        <summary className="speech-head">
          <span className="speech-role clerk">The Scribe — Clerk of the Tribunal</span>
          <span className="speech-preview">{firstSentence(scribeIntro)}</span>
        </summary>
        <div className="speech-body">{scribeIntro}</div>
        <DocketPanel docket={demo.docket} />
      </details>

      {speeches.map((s, i) => (
        <details key={i} className={`speech ${s.role}`}>
          <summary className="speech-head">
            <span className={`speech-role ${s.role}`}>{s.title}</span>
            <span className="speech-preview">{firstSentence(s.text)}</span>
          </summary>
          <div className="speech-body">
            <Markdown text={s.text} />
          </div>
        </details>
      ))}

      {demo.usage && (
        <BillReceipt
          entries={
            [
              { label: 'Prosecutor', usage: demo.usage.prosecutor },
              { label: 'Defense', usage: demo.usage.defense },
              { label: 'Prosecutor (rebuttal)', usage: demo.usage.rebuttal },
              { label: 'Judge', usage: demo.usage.judge },
            ] satisfies BillEntry[]
          }
        />
      )}

      <div className="actions">
        <Link className="link-button" href="/">
          Hold your own trial →
        </Link>
      </div>

      <footer className="footer">
        Precomputed demo · Data: SEC EDGAR XBRL companyfacts · Not investment advice.
      </footer>
    </main>
  )
}
