/**
 * "The Reveal" — breaks the seal on a blind trial: what the tribunal was
 * actually allowed to see at the cutoff, versus what was filed since. Pure
 * arithmetic from `src/sec/facts.ts::buildRealityReport` — never fed to or
 * generated by a model, so it can be trusted as the arbiter of who called it.
 */
import type { RealityReport } from '../trial'

const fmtMoney = (v: number | null): string => {
  if (v === null) return '—'
  const sign = v < 0 ? '-' : ''
  const abs = Math.abs(v)
  if (abs >= 1e9) return `${sign}$${(abs / 1e9).toFixed(2)}B`
  if (abs >= 1e6) return `${sign}$${(abs / 1e6).toFixed(1)}M`
  return `${sign}$${abs.toLocaleString('en-US')}`
}

const fmtPct = (v: number | null): string => (v === null ? '—' : `${v > 0 ? '+' : ''}${v.toFixed(1)}%`)

export function RevealBanner({
  reality,
  revealed,
  onReveal,
}: {
  reality: RealityReport | null
  revealed: boolean
  onReveal: () => void
}) {
  if (!reality) return null
  const rows = reality.deltas.filter((d) => d.cutoffValue !== null || d.latestValue !== null)
  if (!rows.length) return null

  if (!revealed) {
    return (
      <div className="reveal-banner">
        <h3>The seal may now be broken</h3>
        <p>
          The tribunal argued blind, as of {reality.cutoff}. SEC EDGAR has since filed what actually happened next
          — ground truth the agents never saw. Break the seal to compare the verdict against reality.
        </p>
        <button type="button" onClick={onReveal}>
          Break the seal
        </button>
      </div>
    )
  }

  return (
    <div className="reveal-banner">
      <h3>The Reveal</h3>
      <p>What the tribunal knew as of {reality.cutoff}, versus what SEC EDGAR has filed since.</p>
      <table className="reveal-table">
        <thead>
          <tr>
            <th>Metric</th>
            <th>Known at seal</th>
            <th>Filed since</th>
            <th>Change</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((d) => (
            <tr key={d.label}>
              <td>{d.label}</td>
              <td>
                {fmtMoney(d.cutoffValue)}
                {d.cutoffPeriod ? ` (${d.cutoffPeriod})` : ''}
              </td>
              <td>
                {fmtMoney(d.latestValue)}
                {d.latestPeriod ? ` (${d.latestPeriod})` : ''}
              </td>
              <td className={`reveal-delta ${d.changePct !== null && d.changePct < 0 ? 'down' : 'up'}`}>
                {fmtPct(d.changePct)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}
