/**
 * "The Reveal" — breaks the seal on a blind trial: what the tribunal was
 * actually allowed to see at the cutoff, versus what was filed since. Pure
 * arithmetic from `src/sec/facts.ts::buildRealityReport` — never fed to or
 * generated by a model, so it can be trusted as the arbiter of who called it.
 */
import { CALL_LABEL, OUTCOME_LABEL, judgeOutcome, realityCall, tribunalCall, type Call } from '../prophecy'
import type { RealityReport, Verdict } from '../trial'

const fmtMoney = (v: number | null): string => {
  if (v === null) return '—'
  const sign = v < 0 ? '-' : ''
  const abs = Math.abs(v)
  if (abs >= 1e9) return `${sign}$${(abs / 1e9).toFixed(2)}B`
  if (abs >= 1e6) return `${sign}$${(abs / 1e6).toFixed(1)}M`
  return `${sign}$${abs.toLocaleString('en-US')}`
}

const fmtPct = (v: number | null): string => (v === null ? '—' : `${v > 0 ? '+' : ''}${v.toFixed(1)}%`)

/**
 * Settlement of "Beat the Tribunal": three calls side by side (player,
 * tribunal, reality) and an ink-stamped outcome. Pure arithmetic from
 * `app/prophecy.ts`; rendered only when the player actually prophesied
 * and reality can settle it.
 */
function ProphecyOutcomeBlock({
  userCall,
  verdict,
  reality,
}: {
  userCall: Call | null
  verdict: Verdict | null
  reality: RealityReport
}) {
  if (userCall === null || !verdict) return null
  const actual = realityCall(reality)
  if (actual === null) {
    return (
      <p className="prophecy-unsettled">
        Your prophecy of <strong>{CALL_LABEL[userCall]}</strong> stands unsettled — EDGAR has filed no revenue
        figure since the seal to judge it against.
      </p>
    )
  }
  const tribunal = tribunalCall(verdict)
  const outcome = judgeOutcome(userCall, tribunal, actual)
  const userRight = userCall === actual
  const tribunalRight = tribunal === actual
  return (
    <div className="prophecy-outcome">
      <table className="reveal-table">
        <tbody>
          <tr>
            <td>Your prophecy</td>
            <td>{CALL_LABEL[userCall]}</td>
            <td className={`reveal-delta ${userRight ? 'up' : 'down'}`}>{userRight ? 'RIGHT' : 'WRONG'}</td>
          </tr>
          <tr>
            <td>The Tribunal (score {Math.round(verdict.score)})</td>
            <td>{CALL_LABEL[tribunal]}</td>
            <td className={`reveal-delta ${tribunalRight ? 'up' : 'down'}`}>
              {tribunalRight ? 'RIGHT' : 'WRONG'}
            </td>
          </tr>
          <tr>
            <td>Reality (Revenue since seal)</td>
            <td>{CALL_LABEL[actual]}</td>
            <td className="reveal-delta">—</td>
          </tr>
        </tbody>
      </table>
      <div className="prophecy-stamp-row">
        {/* Stamp inks: DISMISSED=green (you were right), SUSTAINED=red (the
            tribunal beat you), PARTIAL=amber (reality fooled you both). */}
        <span className={`stamp ${userRight ? 'DISMISSED' : tribunalRight ? 'SUSTAINED' : 'PARTIAL'}`}>
          {OUTCOME_LABEL[outcome]}
        </span>
      </div>
    </div>
  )
}

export function RevealBanner({
  reality,
  revealed,
  onReveal,
  userCall = null,
  verdict = null,
}: {
  reality: RealityReport | null
  revealed: boolean
  onReveal: () => void
  userCall?: Call | null
  verdict?: Verdict | null
}) {
  if (!reality) return null
  const rows = reality.deltas.filter((d) => d.cutoffValue !== null || d.latestValue !== null)
  if (!rows.length) return null

  if (!revealed) {
    return (
      <div className="reveal-banner">
        <h3>The seal may now be broken</h3>
        <p>
          The tribunal argued blind, as of {reality.cutoff}. SEC EDGAR has since filed what actually happened next
          — ground truth the agents never saw. Break the seal to compare the verdict against reality
          {userCall !== null ? ' — and to settle your prophecy' : ''}.
        </p>
        <button type="button" onClick={onReveal}>
          Break the seal
        </button>
      </div>
    )
  }

  return (
    <div className="reveal-banner">
      <h3>The Reveal</h3>
      <p>What the tribunal knew as of {reality.cutoff}, versus what SEC EDGAR has filed since.</p>
      <table className="reveal-table">
        <thead>
          <tr>
            <th>Metric</th>
            <th>Known at seal</th>
            <th>Filed since</th>
            <th>Change</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((d) => (
            <tr key={d.label}>
              <td>{d.label}</td>
              <td>
                {fmtMoney(d.cutoffValue)}
                {d.cutoffPeriod ? ` (${d.cutoffPeriod})` : ''}
              </td>
              <td>
                {fmtMoney(d.latestValue)}
                {d.latestPeriod ? ` (${d.latestPeriod})` : ''}
              </td>
              <td className={`reveal-delta ${d.changePct !== null && d.changePct < 0 ? 'down' : 'up'}`}>
                {fmtPct(d.changePct)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      <ProphecyOutcomeBlock userCall={userCall} verdict={verdict} reality={reality} />
    </div>
  )
}
