/**
 * Render the tribunal proceedings into Markdown and save DOSSIER_<TICKER>.md
 * in the project root.
 */
import { writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import type { TrialResult } from './run.js'

/** Markdown table cells must not contain pipes or newlines. */
const cell = (s: string): string => s.replace(/\|/g, '\\|').replace(/\s*\n\s*/g, ' ').trim()

export const renderDossier = (trial: TrialResult): string => {
  const { company, peer, brief, peerBrief, bearCase, defense, rebuttal, verdict } = trial
  return [
    `# SEC Tribunal Dossier: ${company.name} (${company.ticker})`,
    '',
    `> CIK ${company.cik10} · Generated ${new Date().toISOString().slice(0, 10)} · Source: SEC EDGAR XBRL companyfacts`,
    '',
    '## Exhibit A — The Evidence',
    '',
    '```text',
    brief,
    '```',
    '',
    ...(peer && peerBrief
      ? [
          `## Exhibit B — Industry Peer: ${peer.name} (${peer.ticker})`,
          '',
          '```text',
          peerBrief,
          '```',
          '',
        ]
      : []),
    '## The Prosecution (Bear Case)',
    '',
    bearCase.trim(),
    '',
    '## The Defense',
    '',
    defense.trim(),
    '',
    "## The Prosecution's Rebuttal",
    '',
    rebuttal.trim(),
    '',
    '## The Verdict',
    '',
    verdict.summary.trim(),
    '',
    '| Charge | Rebuttal | Status |',
    '| --- | --- | --- |',
    ...verdict.charges.map((c) => `| ${cell(c.charge)} | ${cell(c.rebuttal)} | **${c.status}** |`),
    '',
    `### Financial Health Score: ${Math.round(verdict.score)}/100`,
    '',
    '### Recommendation',
    '',
    verdict.recommendation.trim(),
    '',
    '---',
    '',
    '*Generated by SEC Tribunal for Orbio Build Week. Not investment advice.*',
    '',
  ].join('\n')
}

export const saveDossier = async (ticker: string, markdown: string): Promise<string> => {
  const path = resolve(process.cwd(), `DOSSIER_${ticker}.md`)
  await writeFile(path, markdown, 'utf8')
  return path
}
