/**
 * Scoreboard — the public record of the sealed backtest. This page is the
 * tribunal's main proof that it measures something real: every number below
 * is imported at build time from data/backtest-results.json (generated by
 * the backtest run, evidence sealed at a past cutoff) — nothing is fetched,
 * nothing is computed client-side. Pure static server component.
 */
import type { Metadata } from 'next'
import Link from 'next/link'
import { HomeButton } from '../components/home-button'
import results from '../../data/backtest-results.json'

export const metadata: Metadata = {
  title: 'Scoreboard — SEC Tribunal',
  description: 'Sealed backtest results: what a dollar of bought intelligence actually bought.',
}

const fmtPct = (n: number) => `${n.toFixed(1)}%`
const fmtUsd = (n: number) => `$${n.toFixed(2)}`
const fmtPer = (n: number) => n.toFixed(2)

export default function ScoreboardPage() {
  const single = results.configs.single
  const multi = results.configs.multi

  const graded = single.summary.graded
  const totalSpent = single.summary.totalCostUsd + multi.summary.totalCostUsd

  // Unique disagreement tickers across both configurations, keeping the
  // first record seen for each ticker (both configs called them the same way).
  const disagreements = [...single.summary.disagreements, ...multi.summary.disagreements].filter(
    (d, i, all) => all.findIndex((x) => x.ticker === d.ticker) === i,
  )

  const pctOf = (correct: number) => fmtPct((correct / graded) * 100)

  const modelLine = (models: Record<string, string>) =>
    `Prosecutor ${models.prosecutor} · Defense ${models.defense} · Rebuttal ${models.rebuttal} · Judge ${models.judge}`

  return (
    <main className="container">
      <HomeButton />
      <header className="masthead">
        <div className="eyebrow">Court Records · Sealed Trials</div>
        <h1>Scoreboard</h1>
        <p>What a dollar of bought intelligence actually bought.</p>
      </header>

      <div className="speech">
        <article className="md">
          <p>
            <strong>{graded} sealed trials</strong> · <strong>2 tribunal configurations</strong> ·{' '}
            <strong>{fmtUsd(totalSpent)} of CREDIT spent</strong>
          </p>

          <table className="charges">
            <thead>
              <tr>
                <th>Contestant</th>
                <th>Correct calls</th>
                <th>CREDIT spent</th>
                <th>Correct per CREDIT</th>
                <th>Mean |gap|</th>
                <th>Charges sustained</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Always say RISE (naive baseline)</td>
                <td>
                  {single.summary.alwaysRiseCorrect} / {graded} ({pctOf(single.summary.alwaysRiseCorrect)})
                </td>
                <td>{fmtUsd(0)}</td>
                <td>—</td>
                <td>—</td>
                <td>—</td>
              </tr>
              <tr>
                <td>Clerk (code only, no model)</td>
                <td>
                  {single.summary.clerkCorrect} / {graded} ({pctOf(single.summary.clerkCorrect)})
                </td>
                <td>{fmtUsd(0)}</td>
                <td>—</td>
                <td>—</td>
                <td>—</td>
              </tr>
              <tr>
                <td>
                  Tribunal — single provider
                  <br />
                  <small>{modelLine(single.models)}</small>
                </td>
                <td>
                  {single.summary.tribunalCorrect} / {graded} ({pctOf(single.summary.tribunalCorrect)})
                </td>
                <td>{fmtUsd(single.summary.totalCostUsd)}</td>
                <td>{fmtPer(single.summary.correctPerCredit)}</td>
                <td>{single.summary.meanAbsGap.toFixed(1)}</td>
                <td>{fmtPct(single.summary.sustainedRate)}</td>
              </tr>
              <tr>
                <td>
                  Tribunal — three providers
                  <br />
                  <small>{modelLine(multi.models)}</small>
                </td>
                <td>
                  {multi.summary.tribunalCorrect} / {graded} ({pctOf(multi.summary.tribunalCorrect)})
                </td>
                <td>{fmtUsd(multi.summary.totalCostUsd)}</td>
                <td>{fmtPer(multi.summary.correctPerCredit)}</td>
                <td>{multi.summary.meanAbsGap.toFixed(1)}</td>
                <td>{fmtPct(multi.summary.sustainedRate)}</td>
              </tr>
            </tbody>
          </table>

          <h3>Where the models earned their CREDIT</h3>
          <p>On most companies code and tribunal agree. These are the cases where they didn&rsquo;t.</p>
          <ul>
            {disagreements.map((d) => (
              <li key={d.ticker}>
                <strong>{d.ticker}</strong> — the clerk said {d.clerkDirection.toUpperCase()}, the
                tribunal said {d.tribunalDirection.toUpperCase()} — the {d.correctSide} was right.
              </li>
            ))}
          </ul>

          <h3>What we found</h3>
          <p>
            Both tribunals beat the clerk and the naive baseline, and they did it in the same place:
            the two companies where the arithmetic pointed the wrong way.
          </p>
          <p>
            A mixed GPT / Gemini / Claude tribunal cross-examined harder — it sustained a larger
            share of charges and drifted further from the arithmetic — but it called exactly the
            same outcomes as a single-model tribunal, at higher cost. On this sample, diversity
            bought scrutiny, not accuracy.
          </p>
          <p>
            Nineteen companies is a small sample. Treat these as a first measurement, not a verdict
            on the models.
          </p>

          <h3>Excluded</h3>
          <ul>
            {results.excluded.map((e) => (
              <li key={e.ticker}>
                <strong>{e.ticker}</strong> — {e.reason}
              </li>
            ))}
          </ul>
        </article>
      </div>

      <footer className="footer">
        Evidence sealed at {results.cutoff} · commit {results.commit} · raw data:
        data/backtest-results.json · <Link href="/methodology">Methodology</Link>
      </footer>
    </main>
  )
}
